apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-website
  labels:
    app: hugo-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugo-website
  template:
    metadata:
      labels:
        app: hugo-website
    spec:
      containers:
      - name: hugo-website
        image: nishantaqa/newstack:latest
        ports:
        - containerPort: 1313

