apiVersion: v1
kind: Service
metadata:
  name: hugo-website-service
spec:
  type: NodePort
  selector:
    app: hugo-website
  ports:
  - name: http
    port: 1313
    targetPort: 1313
    protocol: TCP


